import { encodeDeployData, encodeFunctionData, type Address, type Hex } from "viem";
import DylCollectionArtifact from "./contracts/DylCollection.json";
import AlbumBuyerArtifact from "./contracts/AlbumBuyer.json";
import ERC1967ProxyArtifact from "./contracts/ERC1967Proxy.json";

// Real deployed contract source: onchain/contracts/DylCollection.sol,
// onchain/contracts/AlbumBuyer.sol. ABI/bytecode here are generated by
// `npm run build` in onchain/ (scripts/export-artifacts.ts) — never hand-edit
// these three JSON files, regenerate them instead.

export interface RawTx {
  to?: Address;
  data: Hex;
  value: bigint;
}

// Root tsconfig targets es2017 — bigint LITERAL syntax (0n) isn't valid
// TypeScript below es2020, same reason the rest of this codebase always
// calls BigInt(...) instead (see components/SwapCard.tsx, BurnWalletChecker.tsx).
const ZERO = BigInt(0);

const DylCollectionAbi = DylCollectionArtifact.abi;
const DylCollectionBytecode = DylCollectionArtifact.bytecode as Hex;
const AlbumBuyerAbi = AlbumBuyerArtifact.abi;
const AlbumBuyerBytecode = AlbumBuyerArtifact.bytecode as Hex;
const ERC1967ProxyAbi = ERC1967ProxyArtifact.abi;
const ERC1967ProxyBytecode = ERC1967ProxyArtifact.bytecode as Hex;

/** Step 1 of a UUPS deploy: the implementation contract itself, no constructor args. */
export function buildDeployImplementationTx(): RawTx {
  const data = encodeDeployData({
    abi: DylCollectionAbi,
    bytecode: DylCollectionBytecode,
    args: [],
  });
  return { data, value: ZERO };
}

/**
 * Step 2 of a UUPS deploy: OpenZeppelin's stock ERC1967Proxy pointed at the
 * implementation from step 1, with encoded `initialize(...)` calldata so the
 * proxy is never left uninitialized (ERC1967Proxy's own constructor reverts
 * on empty `_data`). The address this transaction creates is the permanent,
 * real collection address — the one that goes in lib/admin.ts and everywhere
 * else, never the implementation address from step 1.
 */
export function buildDeployProxyTx(params: {
  implementationAddress: Address;
  name: string;
  symbol: string;
  admin: Address;
  initialMintPriceWei: bigint;
  initialMetadataBaseURI: string;
}): RawTx {
  const initData = encodeFunctionData({
    abi: DylCollectionAbi,
    functionName: "initialize",
    args: [
      params.name,
      params.symbol,
      params.admin,
      params.initialMintPriceWei,
      params.initialMetadataBaseURI,
    ],
  });
  const data = encodeDeployData({
    abi: ERC1967ProxyAbi,
    bytecode: ERC1967ProxyBytecode,
    args: [params.implementationAddress, initData],
  });
  return { data, value: ZERO };
}

/**
 * Upgrade: deploy a new implementation separately (buildDeployImplementationTx
 * against the new contract's own artifact), then call this against the
 * EXISTING proxy address. Run onchain/scripts/validate-upgrade.ts against the
 * real proxy first — this is the one required manual safety check the
 * browser-signed path has no automatic equivalent for.
 */
export function buildUpgradeTx(proxyAddress: Address, newImplementationAddress: Address): RawTx {
  const data = encodeFunctionData({
    abi: DylCollectionAbi,
    functionName: "upgradeToAndCall",
    args: [newImplementationAddress, "0x"],
  });
  return { to: proxyAddress, data, value: ZERO };
}

/**
 * The real public, payable mint — anyone can call this, `msg.value` must
 * equal `mintPriceWei * quantity` exactly (the contract reverts otherwise,
 * see onchain/contracts/DylCollection.sol `IncorrectPayment`). `valueWei`
 * is the caller's responsibility to compute correctly from a live read of
 * the deployed contract's own `mintPriceWei` — this function does not
 * fetch or validate it, same "pure tx builder, no chain reads" shape as
 * every other function in this file.
 */
export function buildMintTx(proxyAddress: Address, trackId: bigint, quantity: bigint, to: Address, valueWei: bigint): RawTx {
  const data = encodeFunctionData({
    abi: DylCollectionAbi,
    functionName: "mint",
    args: [trackId, quantity, to],
  });
  return { to: proxyAddress, data, value: valueWei };
}

/** Editions #1-10, admin wallet only, hard-capped on-chain at 10 regardless of quantity requested. */
export function buildAdminMintTx(
  proxyAddress: Address,
  trackId: bigint,
  quantity: bigint,
  to: Address
): RawTx {
  const data = encodeFunctionData({
    abi: DylCollectionAbi,
    functionName: "adminMint",
    args: [trackId, quantity, to],
  });
  return { to: proxyAddress, data, value: ZERO };
}

export function buildSetMintPriceTx(proxyAddress: Address, newPriceWei: bigint): RawTx {
  const data = encodeFunctionData({
    abi: DylCollectionAbi,
    functionName: "setMintPrice",
    args: [newPriceWei],
  });
  return { to: proxyAddress, data, value: ZERO };
}

export function buildSetMetadataBaseURITx(proxyAddress: Address, newBaseURI: string): RawTx {
  const data = encodeFunctionData({
    abi: DylCollectionAbi,
    functionName: "setMetadataBaseURI",
    args: [newBaseURI],
  });
  return { to: proxyAddress, data, value: ZERO };
}

export function buildWithdrawTx(proxyAddress: Address, to: Address): RawTx {
  const data = encodeFunctionData({
    abi: DylCollectionAbi,
    functionName: "withdraw",
    args: [to],
  });
  return { to: proxyAddress, data, value: ZERO };
}

/** AlbumBuyer is plain, non-upgradeable — one normal contract-creation transaction. */
export function buildDeployAlbumBuyerTx(): RawTx {
  const data = encodeDeployData({
    abi: AlbumBuyerAbi,
    bytecode: AlbumBuyerBytecode,
    args: [],
  });
  return { data, value: ZERO };
}

export function buildAlbumBatchMintTx(params: {
  albumBuyerAddress: Address;
  collectionAddress: Address;
  trackIds: bigint[];
  quantities: bigint[];
  to: Address;
  totalValueWei: bigint;
}): RawTx {
  const data = encodeFunctionData({
    abi: AlbumBuyerAbi,
    functionName: "batchMint",
    args: [params.collectionAddress, params.trackIds, params.quantities, params.to],
  });
  return { to: params.albumBuyerAddress, data, value: params.totalValueWei };
}

export { DylCollectionAbi, AlbumBuyerAbi, ERC1967ProxyAbi };
